# Generated by Django 2.2.2 on 2019-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_info',
            name='phone_from',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='photo_info',
            name='phone_to',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
