# Generated by Django 2.2.2 on 2019-06-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190616_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='print',
        ),
    ]
