# Generated by Django 2.2.2 on 2019-06-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_photo_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_info',
            name='message',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
