# Generated by Django 2.2.2 on 2019-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_photo_info_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_info',
            name='message',
            field=models.CharField(max_length=40),
        ),
    ]
