# Generated by Django 2.2.2 on 2019-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190619_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
