# Generated by Django 2.2.2 on 2019-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_photo_upload_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_info',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
