# Generated by Django 2.2.2 on 2019-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_photo_info_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='random_url',
            field=models.CharField(default='asdfg', max_length=15),
            preserve_default=False,
        ),
    ]
